### PR TITLE
Code Review - Game logic branch

### PR DESCRIPTION
**Pull request by javitocor**
In "game logic" branch we added the basic logic for the game and we make it interactive to the users.
The program checks all the possibles scenarios giving a proper message in every case.
And asks for a new game after it ends.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice Progress :clap: 
Your game works and looks fine. However, we need to make a few changes before we can merge this PR.
- [x] game does not detect invalid moves. Entering a choice like 5 instead of a1 or a2 simply changes player turn but does not prompt the current player to enter a valid input.
Tell the player their input is invalid and give them suggestions of valid moves like c1, c2, etc.
### [OPTIONAL]
- [ ] Instead of marking repeated move as invalid, you could inform the player the given spot is taken. It's more informative

### Martin Afani

**Comment by javitocor** [comment]
Fixed alert for invalid inputs

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Hi!

Great work and well done addressing the previous review, now when I chose an invalid move the game does not changes the player turn, but 😖... as also mentioned in the previous review by @whiz25 , you also need to inform about invalid moves:

> * [x] Tell the player their input is invalid.

At this point, no matter what I enter for `your move`, I always get `great move!`, which is not the best feedback and is really confusing.

Status: __Request changes__.

**Review by MauricioRobayo — APPROVED** [review]
Well done!

The project looks great and all requirements are met.

Status: __Approved__.

**Comment by MauricioRobayo** [comment]
Hi @javitocor @Spayco !

There were very important requirements missing in this milestone.

I am really sorry about that and wanted to invite you to revisit your project to get the most out of it.

So, when you have the time, please double-check the following:

* [ ] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] All classes are kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing). Avoid long methods that are doing multiple steps of the game process. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/single_responsibility.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

I want you to get the most out of the program, that's why I highly encourage you to revisit this project and update it accordingly. No need to request for code review, just keep accountable to yourselves and your learning process.

**Pull request merged**
